const classes = [
  {name: 'The Fool',"imports":[]},
  {name: 'The Magician',"imports":[]},
  {name: 'The High Priestess',"imports":[]},
  {name: 'The Empress',"imports":[]},
  {name: 'The Emperor',"imports":[]},
  {name: 'The Hierophant',"imports":[]},
  {name: 'The Lovers',"imports":[]},
  {name: 'The Chariot',"imports":[]},
  {name: 'Strength',"imports":[]},
  {name: 'The Hermit',"imports":[]},
  {name: 'Wheel of Fortune',"imports":[]},
  {name: 'Justice',"imports":[]},
  {name: 'The Hanged Man',"imports":[]},
  {name: 'Death',"imports":[]},
  {name: 'Temperance',"imports":[]},
  {name: 'The Devil',"imports":[]},
  {name: 'The Tower',"imports":[]},
  {name: 'The Star',"imports":[]},
  {name: 'The Moon',"imports":[]},
  {name: 'The Sun',"imports":[]},
  {name: 'Judgement',"imports":[]},
  {name: 'The World',"imports":[]},
  {name: 'King of Cups',"imports":[]},
  {name: 'Queen of Cups',"imports":[]},
  {name: 'Knight of Cups',"imports":[]},
  {name: 'Page of Cups',"imports":[]},
  {name: 'Ten of Cups',"imports":[]},
  {name: 'Nine of Cups',"imports":[]},
  {name: 'Eight of Cups',"imports":[]},
  {name: 'Seven of Cups',"imports":[]},
  {name: 'Six of Cups',"imports":[]},
  {name: 'Five of Cups',"imports":[]},
  {name: 'Four of Cups',"imports":[]},
  {name: 'Three of Cups',"imports":[]},
  {name: 'Two of Cups',"imports":[]},
  {name: 'Ace of Cups',"imports":[]},
  {name: 'King of Swords',"imports":[]},
  {name: 'Queen of Swords',"imports":[]},
  {name: 'Knight of Swords',"imports":[]},
  {name: 'Page of Swords',"imports":[]},
  {name: 'Ten of Swords',"imports":[]},
  {name: 'Nine of Swords',"imports":[]},
  {name: 'Eight of Swords',"imports":[]},
  {name: 'Seven of Swords',"imports":[]},
  {name: 'Six of Swords',"imports":[]},
  {name: 'Five of Swords',"imports":[]},
  {name: 'Four of Swords',"imports":[]},
  {name: 'Three of Swords',"imports":[]},
  {name: 'Two of Swords',"imports":[]},
  {name: 'Ace of Swords',"imports":[]},
  {name: 'King of Wands',"imports":[]},
  {name: 'Queen of Wands',"imports":[]},
  {name: 'Knight of Wands',"imports":[]},
  {name: 'Page of Wands',"imports":[]},
  {name: 'Ten of Wands',"imports":[]},
  {name: 'Nine of Wands',"imports":[]},
  {name: 'Eight of Wands',"imports":[]},
  {name: 'Seven of Wands',"imports":[]},
  {name: 'Six of Wands',"imports":[]},
  {name: 'Five of Wands',"imports":[]},
  {name: 'Four of Wands',"imports":[]},
  {name: 'Three of Wands',"imports":[]},
  {name: 'Two of Wands',"imports":[]},
  {name: 'Ace of Wands',"imports":[]},
  {name: 'King of Pentacles',"imports":[]},
  {name: 'Queen of Pentacles',"imports":[]},
  {name: 'Knight of Pentacles',"imports":[]},
  {name: 'Page of Pentacles',"imports":[]},
  {name: 'Ten of Pentacles',"imports":[]},
  {name: 'Nine of Pentacles',"imports":[]},
  {name: 'Eight of Pentacles',"imports":[]},
  {name: 'Seven of Pentacles',"imports":[]},
  {name: 'Six of Pentacles',"imports":[]},
  {name: 'Five of Pentacles',"imports":[]},
  {name: 'Four of Pentacles',"imports":[]},
  {name: 'Three of Pentacles',"imports":[]},
  {name: 'Two of Pentacles',"imports":[]},
  {name: 'Ace of Pentacles',"imports":[]}
]

const tarots = {
  1: 'The Fool',
  2: 'The Magician',
  3: 'The High Priestess',
  4: 'The Empress',
  5: 'The Emperor',
  6: 'The Hierophant',
  7: 'The Lovers',
  8: 'The Chariot',
  9: 'Strength',
  10: 'The Hermit',
  11: 'Wheel of Fortune',
  12: 'Justice',
  13: 'The Hanged Man',
  14: 'Death',
  15: 'Temperance',
  16: 'The Devil',
  17: 'The Tower',
  18: 'The Star',
  19: 'The Moon',
  20: 'The Sun',
  21: 'Judgement',
  22: 'The World'
}

module.exports = { tarots, classes }